---
- name: Transfer and execute a script.
  hosts: 192.168.0.54
  become: yes 
  become_method: sudo
  become_user: root 
  gather_facts: yee

  tasks:
     - name: Transfer the script
       copy: src=/home/ansadmin/Script/Update_Servers.sh dest=/home/ansadmin mode=0777

     - name: Execute the script
       command: sudo sh /home/ansadmin/Update_Servers.sh
...
